# Generated by Django 5.2.4 on 2025-08-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wapp.player')),
            ],
        ),
    ]
